basePath: /v1
definitions:
  main.CreateUserTokenPayload:
    properties:
      email:
        maxLength: 255
        type: string
      password:
        maxLength: 72
        minLength: 3
        type: string
    required:
    - email
    - password
    type: object
  main.RegisterUserPayload:
    properties:
      email:
        maxLength: 255
        type: string
      name:
        maxLength: 100
        type: string
      password:
        maxLength: 72
        minLength: 3
        type: string
      username:
        maxLength: 100
        type: string
    required:
    - email
    - name
    - password
    - username
    type: object
  main.UserWithToken:
    properties:
      bio:
        type: string
      created_at:
        type: string
      email:
        type: string
      id:
        type: integer
      is_active:
        type: boolean
      name:
        type: string
      profile_picture:
        items:
          type: integer
        type: array
      role:
        type: string
      token:
        type: string
      username:
        type: string
    type: object
  store.Comment:
    properties:
      content:
        type: string
      created_at:
        type: string
      id:
        type: integer
      post_id:
        type: integer
      user:
        $ref: '#/definitions/store.User'
      user_id:
        type: integer
    type: object
  store.FeedItem:
    properties:
      author:
        type: string
      category:
        type: string
      id:
        type: integer
      introduction:
        type: string
      thumbnail_image:
        items:
          type: integer
        type: array
      title:
        type: string
      updated_at:
        type: string
      user_id:
        type: integer
    type: object
  store.Post:
    properties:
      category:
        type: string
      comments:
        items:
          $ref: '#/definitions/store.Comment'
        type: array
      content:
        type: string
      created_at:
        type: string
      id:
        type: integer
      introduction:
        type: string
      thumbnail_image:
        items:
          type: integer
        type: array
      title:
        type: string
      updated_at:
        type: string
      user_id:
        type: integer
      version:
        type: integer
    type: object
  store.User:
    properties:
      bio:
        type: string
      created_at:
        type: string
      email:
        type: string
      id:
        type: integer
      is_active:
        type: boolean
      name:
        type: string
      profile_picture:
        items:
          type: integer
        type: array
      role:
        type: string
      username:
        type: string
    type: object
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: API for my blog post
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Blog Post API
paths:
  /authentication/token:
    post:
      consumes:
      - application/json
      description: Create a token
      parameters:
      - description: User credentials
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/main.CreateUserTokenPayload'
      produces:
      - application/json
      responses:
        "201":
          description: Token
          schema:
            type: string
        "400":
          description: Bad Request
          schema: {}
        "401":
          description: Unauthorized
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: Create a token
      tags:
      - authentication
  /authentication/user:
    post:
      consumes:
      - application/json
      description: Register a user
      parameters:
      - description: User credentials
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/main.RegisterUserPayload'
      produces:
      - application/json
      responses:
        "201":
          description: User registered
          schema:
            $ref: '#/definitions/main.UserWithToken'
        "400":
          description: Bad Request
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: Register a user
      tags:
      - authentication
  /comments:
    post:
      consumes:
      - application/json
      description: Create a new comment on a post with the provided details
      parameters:
      - description: Post ID
        in: path
        name: postID
        required: true
        type: integer
      - description: User ID
        in: body
        name: user_id
        required: true
        schema:
          type: integer
      - description: Comment Content
        in: body
        maxLength: 300
        name: content
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "201":
          description: Successfully created comment
          schema:
            $ref: '#/definitions/store.Comment'
        "400":
          description: Invalid request, the request data was incorrect or malformed
          schema: {}
        "500":
          description: Internal server error, the server encountered a problem
          schema: {}
      security:
      - ApiKeyAuth: []
      summary: Create a new comment
      tags:
      - comments
  /feed:
    get:
      consumes:
      - application/json
      description: Retrieve a paginated feed of posts with optional filters for category
        and search
      parameters:
      - description: Number of posts to retrieve (default is 6, max is 20)
        in: query
        maximum: 20
        minimum: 1
        name: limit
        type: integer
      - description: Offset for pagination (default is 0)
        in: query
        name: offset
        type: integer
      - description: Sort order (default is 'desc', options are 'asc' or 'desc')
        in: query
        name: sort
        type: string
      - description: Category to filter posts by
        in: query
        name: category
        type: string
      - description: Search term to filter posts by (max length is 100)
        in: query
        name: search
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Successfully retrieved the posts feed
          schema:
            items:
              $ref: '#/definitions/store.FeedItem'
            type: array
        "400":
          description: Invalid request, the request data was incorrect or malformed
          schema: {}
        "500":
          description: Internal server error, the server encountered a problem
          schema: {}
      security:
      - ApiKeyAuth: []
      summary: Get post feed
      tags:
      - posts
  /health:
    get:
      consumes:
      - application/json
      description: Check the health status of the server, environment, and version
      produces:
      - application/json
      responses:
        "200":
          description: Returns server health status, environment, and version
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error, the server encountered a problem
          schema: {}
      summary: Health check
      tags:
      - health
  /posts:
    post:
      consumes:
      - application/json
      description: Creates a new post with the provided details
      parameters:
      - description: Post Title
        in: body
        maxLength: 100
        name: title
        required: true
        schema:
          type: string
      - description: Post Introduction
        in: body
        maxLength: 120
        name: introduction
        required: true
        schema:
          type: string
      - description: Post Content
        in: body
        maxLength: 1000
        name: content
        required: true
        schema:
          type: string
      - description: Post Category
        in: body
        maxLength: 100
        name: category
        required: true
        schema:
          type: string
      - description: Thumbnail Image
        in: body
        name: thumbnail_image
        schema:
          type: string
      produces:
      - application/json
      responses:
        "201":
          description: Successfully created post
          schema:
            $ref: '#/definitions/store.Post'
        "400":
          description: Invalid request, the request data was incorrect or malformed
          schema: {}
        "500":
          description: Internal server error, the server encountered a problem
          schema: {}
      security:
      - ApiKeyAuth: []
      summary: Create a post
      tags:
      - posts
  /posts/{postID}:
    delete:
      consumes:
      - application/json
      description: Delete a post by its ID
      parameters:
      - description: Post ID
        in: path
        name: postID
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "204":
          description: "No Content\"\t\"Successfully deleted post, no content returned"
        "400":
          description: Invalid request, the request data was incorrect or malformed
          schema: {}
        "404":
          description: Post not found
          schema: {}
        "500":
          description: Internal server error, the server encountered a problem
          schema: {}
      security:
      - ApiKeyAuth: []
      summary: Delete a post
      tags:
      - posts
    get:
      consumes:
      - application/json
      description: Retrieve a post along with its comments
      parameters:
      - description: Post ID
        in: path
        name: postID
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Successfully fetched post
          schema:
            $ref: '#/definitions/store.Post'
        "400":
          description: Invalid request, the request data was incorrect or malformed
          schema: {}
        "404":
          description: Post not found
          schema: {}
        "500":
          description: Internal server error, the server encountered a problem
          schema: {}
      security:
      - ApiKeyAuth: []
      summary: Get a post
      tags:
      - posts
    put:
      consumes:
      - application/json
      description: Update an existing post with new details
      parameters:
      - description: Post ID
        in: path
        name: postID
        required: true
        type: integer
      - description: Post Title
        in: body
        maxLength: 100
        name: title
        schema:
          type: string
      - description: Post Introduction
        in: body
        maxLength: 120
        name: introduction
        schema:
          type: string
      - description: Post Content
        in: body
        maxLength: 1000
        name: content
        schema:
          type: string
      - description: Post Category
        in: body
        maxLength: 100
        name: category
        schema:
          type: string
      - description: Thumbnail Image
        in: body
        name: thumbnail_image
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: Successfully updated post
          schema:
            $ref: '#/definitions/store.Post'
        "400":
          description: Invalid request, the request data was incorrect or malformed
          schema: {}
        "404":
          description: Post not found
          schema: {}
        "409":
          description: 'Conflict: The request could not be completed due to a conflict'
          schema: {}
        "500":
          description: Internal server error, the server encountered a problem
          schema: {}
      security:
      - ApiKeyAuth: []
      summary: Update a post
      tags:
      - posts
  /users/{id}:
    get:
      consumes:
      - application/json
      description: Fetch a user profile by ID
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/store.User'
        "400":
          description: Bad Request
          schema: {}
        "404":
          description: Not Found
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      security:
      - ApiKeyAuth: []
      summary: Fetch a user profile
      tags:
      - users
  /users/{userID}:
    patch:
      consumes:
      - application/json
      description: Update the details of an existing user (partial update)
      parameters:
      - description: User ID
        in: path
        name: userID
        required: true
        type: integer
      - description: Name
        in: body
        maxLength: 72
        name: name
        schema:
          type: string
      - description: Username
        in: body
        maxLength: 72
        name: username
        schema:
          type: string
      - description: Email
        format: email
        in: body
        maxLength: 120
        name: email
        schema:
          type: string
      - description: Bio
        in: body
        maxLength: 120
        name: bio
        schema:
          type: string
      - description: Profile Picture (base64 encoded)
        in: body
        maxLength: 1000000
        name: profile_picture
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: Successfully updated user
          schema:
            $ref: '#/definitions/store.User'
        "400":
          description: Invalid request, the request data was incorrect or malformed
          schema: {}
        "404":
          description: User not found
          schema: {}
        "500":
          description: Internal server error, the server encountered a problem
          schema: {}
      security:
      - ApiKeyAuth: []
      summary: Update an existing user
      tags:
      - users
  /users/activate/{token}:
    put:
      consumes:
      - application/json
      description: Activate/Register a user by invitation token
      parameters:
      - description: Invitation token
        in: path
        name: token
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: User activated
          schema:
            type: string
        "404":
          description: Not Found
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      security:
      - ApiKeyAuth: []
      summary: Activate/Register a user
      tags:
      - users
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
